### ISSUE TITLE
2015-12-05: globalni-registrace-filteru

### ISSUE THREAD

**Issue by paveljanda** [contributte/planette-site#55]
Pokud chceme mít dostupný filtr (helper) ve všech šablonách presenteru, komponent i všude, kde vytváříme šablony přes služby typu `ITemplateFactory` nebo `ILatteFactory`, můžeme filtr registrovat globálně v `config.neon`.

[Někteří považují](https://github.com/nette/web-content/issues/263#issuecomment-83167618) tuto techniku za antipattern.

```
services:
        latte.latteFactory:
        setup:
                        - addFilter(nazevFilteru, callback)
```

Jako callback můžeme uvést klasickou funkci (např. `count`), statickou metodu (`[Helpers, doSth]`) nebo metodu jiné služby (`@someService::doSth`).

Použitelné pro Nette >= 2.3
